// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: pusher.proto

package server

import (
	"context"

	"puhser/internal/logic"
	"puhser/internal/svc"
	"puhser/proto/push"
)

type PushMessageServiceServer struct {
	svcCtx *svc.ServiceContext
	push.UnimplementedPushMessageServiceServer
}

func NewPushMessageServiceServer(svcCtx *svc.ServiceContext) *PushMessageServiceServer {
	return &PushMessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PushMessageServiceServer) PushMessage(ctx context.Context, in *push.PushMessageReq) (*push.PushMessageResp, error) {
	l := logic.NewPushMessageLogic(ctx, s.svcCtx)
	return l.PushMessage(in)
}
