// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: in.proto

package server

import (
	"context"

	"InnerGetWay/internal/logic"
	"InnerGetWay/internal/svc"
	"InnerGetWay/proto/in"
)

type PushMessageServiceServer struct {
	svcCtx *svc.ServiceContext
	in.UnimplementedPushMessageServiceServer
}

func NewPushMessageServiceServer(svcCtx *svc.ServiceContext) *PushMessageServiceServer {
	return &PushMessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PushMessageServiceServer) PushMessage(ctx context.Context, in *in.PushMessageReq) (*in.PushMessageResp, error) {
	l := logic.NewPushMessageLogic(ctx, s.svcCtx)
	return l.PushMessage(in)
}
